model_name: models/Qwen2.5-0.5B
train_file: data/train.json
output_dir: results/qwen2.5-0.5b-lora-mixed-1k

max_seq_length: 512
num_train_epochs: 2
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 0.0002
logging_steps: 10
save_steps: 100

lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
